name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Hello, world!"
      - name: Simulating an error
        run: echo "About to fail" ; exit 1
      - name: Another Greeting
        run: echo "Hello, world!"
